# Generated by Django 4.0.1 on 2022-01-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('worker_profile', '0003_remove_worker_id_alter_worker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.ManyToManyField(to='categories.Category'),
        ),
    ]
