# Generated by Django 4.0.1 on 2022-01-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profile', '0004_worker_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(default='test@mail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
