# Generated by Django 4.0.1 on 2022-01-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_profile', '0005_worker_email_alter_worker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='first_name',
            field=models.CharField(default='Master', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='last_name',
            field=models.CharField(default='Master', max_length=100),
            preserve_default=False,
        ),
    ]
