# Generated by Django 4.0.1 on 2022-01-30 19:16

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Tuzla', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='Tuzla', max_length=63),
            preserve_default=False,
        ),
    ]
